learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
'''定义learning_logs的url模式。'''
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # 显示所有的主题
    path('topics/', views.topics, name='topics'),
    # 特定主题的详细页面
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # 用于添加新主题的页面
    path('new_topic/', views.new_topic, name='new_topic'),
    # 用于添加新条目
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # 用于编辑条目的页面。
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]


users/urls.py
'''为应用程序users定义URL模式'''
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # 包含默认的身份验证URL
    path('', include('django.contrib.auth.urls')),
    # 注册页面
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models

class Topic(models.Model):
    '''用户学习的主题'''
    text = models.CharField(max_length=200)
    data_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.text

class Entry(models.Model):
    '''学到的有关某个主题的具体知识。'''
    # .foreignkey是一个数据库术语，将每个条目关联到Topic，on_delete让删除主题时同时删除所有与之相关的条目。
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    # meta类用于存储用于管理模型的额外信息
    class meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"


# Create your models here.

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from django.forms import fields

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ' '}
        widgets = {'text': forms.Textarea(attrs={'cols': 80 })}

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required

def index(request):
    '''学习笔记的主页'''
    return render(request, 'learning_logs/index.html')
@login_required
def topics(request):
    '''显示所有主题。'''
    topics = Topic.objects.order_by('data_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    '''显示单个主题及其所有的条目'''
    topic = Topic.objects.get(id=topic_id)
    # 将获取到的与主题相关的条目，并根据data_added进行排序，减号表示按照降序排列
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
    '''添加新的主题'''
    if request.method != 'POST':
        # 当请求不是post，那么就是get,所以给一个新的表单
        form = TopicForm()
    else:
        # 当是post请求的时候，对提交的post表单进行处理
        form = TopicForm(data=request.POST)
        #  方法is_valid核实用户填写了所有必不可少的字段，且输入的数据与要求的字段类型一致
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    # 将form表单的内容赋值给context
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != "POST":
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

def edit_entry(request, entry_id):
    '''编辑现有条目'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # 初次请求使用现有条目填充表单
        form = EntryForm(instance=entry)
    else:
        # 如果要是post的话，用原先的内容先填充表单，对后面post提交的内容进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)
# Create your views here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    '''注册新用户'''
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页。
            login(request, new_user)
            return redirect('learning_logs:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

# Create your views here.

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang='en'>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
    <title>Log天涯</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
      Log天涯</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics'%}">主题</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">你好，{{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">注销</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">注册</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">登录</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>
</html>



learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
  <p>编辑条目：</p>
{% endblock page_header%}

{% block content %}

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button name="submit" class="btn btn-primary btn-sm">保存更改</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <div class="jumbotron">
    <h2 class="display-3">{Log}天涯~ <br/>发现自己的足迹。</h2>

    <p class="lead">欢迎来到LOG天涯，在这里添加你的ideas,追踪自己的历史。无论你学习了什么，
                    或者有任何感兴趣的事情，都可以进行分享和记录，Go For It.</p>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">快来注册吧！&raquo;</a>
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock page_header%}

{% block content%}
  <h4>添加一个新条目：</h4>
  <form method='POST' action="{% url 'learning_logs:new_entry' topic.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary btn-sm">添加条目</button>
    {% endbuttons %}
    
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>添加一个新的主题：</h2>
{% endblock page_header%}

{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method='POST' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary btn-sm">添加主题</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>主题：{{ topic }}</h3>
{% endblock page_header%}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">添加新条目</a>  
  </p>
  
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'H:i M d, Y' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑条目</a></small>
      </h4>
      <!--设置每个项目的样式，类似卡片的样式-->
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>这个主题还没有相关条目。</p>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>主题</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in topics%}
      <li><h3>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </h3></li>
    {% empty %}
      <li><h3>没有添加话题。</h3></li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">添加一个新的主题</a></h3>
{% endblock content %}